# Generated by Django 4.1.2 on 2024-06-27 03:23

from django.db import migrations, models
import django.db.models.deletion
import ventas.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comuna', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Consola',
            fields=[
                ('id_consola', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Videojuego',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nom_juego', models.CharField(max_length=100)),
                ('stock_juego', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('image', models.ImageField(upload_to=ventas.models.get_image_path)),
                ('precio', models.IntegerField()),
                ('id_consola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.consola')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('rut', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('a_paterno', models.CharField(max_length=100)),
                ('a_materno', models.CharField(max_length=100)),
                ('direccion', models.TextField()),
                ('email1', models.EmailField(max_length=254)),
                ('cel1', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=100)),
                ('id_comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.comuna')),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id_compra', models.AutoField(primary_key=True, serialize=False)),
                ('stock', models.IntegerField()),
                ('direccion_envio', models.TextField()),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.videojuego')),
                ('rut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.usuario')),
            ],
        ),
    ]
