# Generated by Django 4.1.2 on 2024-06-28 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_carrito_elementocarrito'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('rut', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('a_paterno', models.CharField(max_length=100)),
                ('a_materno', models.CharField(max_length=100)),
                ('direccion', models.TextField()),
                ('email1', models.EmailField(max_length=254)),
                ('cel1', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=100)),
                ('id_comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.comuna')),
            ],
        ),
    ]
