# Generated by Django 4.1.2 on 2024-06-29 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_alter_usuario_direccion_alter_vendedor_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email1',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='email1',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
