# Generated by Django 4.1.2 on 2024-07-01 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_alter_carrito_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compra',
            old_name='stock',
            new_name='cantidad',
        ),
        migrations.RenameField(
            model_name='compra',
            old_name='rut',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='compra',
            old_name='id_producto',
            new_name='videojuego',
        ),
    ]
